services:
  CodingExercise:
    image: webdevops/php-nginx:8.3
    links:
      - database
    volumes:
      - ./laravel/:/app
    working_dir: /app
    ports:
      - "9033:80"
    environment:
      - WEB_DOCUMENT_ROOT=/app/public

  database:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=calender
      - MYSQL_USER=user
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    links:
      - database
    ports:
      - "8020:80"
    environment:
      PMA_USER: root
      PMA_PASSWORD: secret
      PMA_HOST: database
      PMA_ARBITRARY: 1
